import re
import json

def extractDataFromNgSpiceOutput(pathToFile):

    """ Parses the output file generated by ngspice and
    returns a json containing points to plot graph.
    """

    try:
        with open(pathToFile,'r') as f:
            fContents = f.readlines()
            jsonData = {"total_tables":0,"data":[]}
            # depthLevel = 0
            curernt_headers = []
            total_number_of_tables = 0
            # for line in fContents:
            #     m = re.search('Index',line)
            #     if(m):
            #         headerContents = line.split()
            #         #subtract 2 to remove Time and Index from the total length of list
            #         totalNumberOfTables = len(headerContents) - 2
            #         jsonData['totalNumberOfTables'] = totalNumberOfTables
            #         jsonData["headers"] = headerContents
            #         jsonData["dataPoints"]= []
            #         depthLevel = len(headerContents)
            #         for i in range(depthLevel):
            #             jsonData['dataPoints'].append([])

            #     m = re.match('[0-9]+',line)
            #     if(m):
            #         d = (line.split())
            #         for i in range(len(headerContents)):
            #             jsonData['dataPoints'][i].append(d[i])

            for line in fContents:
                contents_of_line = line.split()
                if('Index' in contents_of_line):
                    line_set = remove_duplicate_items_from_list(contents_of_line)

                    if(line_set != curernt_headers):
                        curernt_headers = line_set
                       

                        jsonData["data"].append({"labels":[],"x":[],"y":[]})
                        index = len(jsonData["data"]) - 1
                        for x in range(2,len(curernt_headers)):
                            jsonData["data"][index]["y"].append([])
                        
                        for x in range(1,len(curernt_headers)):
                            jsonData["data"][index]["labels"].append(curernt_headers[x])
                            total_number_of_tables += 1
                        

                        
                        
                else:
                    m = re.match('[0-9]+',line)
                    if(m):
                        d = (contents_of_line)
                        
                        index = len(jsonData["data"]) - 1
                        data = jsonData["data"][index]
                        data["x"].append(contents_of_line[1])

                        for x in range(len(data["y"])):
                            data["y"][x].append(contents_of_line[x+2])

                       
                      
        jsonData["total_tables"] = total_number_of_tables - len(jsonData["data"])
        return json.dumps(jsonData)

    except IOError as e:
        return "Cannot open file."


def remove_duplicate_items_from_list(line_list):
    res = []
    for i in line_list:
        if i not in res:
            res.append(i)
    return res

#for testing provide the filepath as command line argument
if __name__ == "__main__":
    # import sys
    # filePath = sys.argv[1]
    print(extractDataFromNgSpiceOutput("./sample_files/data.txt"))
