import re
import sys
from typing import Any, Dict, List, Optional


def extract_data_from_ngspice_output(pathToFile: str) -> Dict[str, Any]:
    """ Parses the output file generated by ngspice and
    returns a json containing points to plot graph.
    """

    try:
        with open(pathToFile, 'r') as f:
            f_contents: List[str] = f.readlines()
            graph: bool = False

            curernt_headers: List[str] = []
            total_number_of_tables: int = 0
            if(len(f_contents) > 3):
                if('---' in f_contents[2]):
                    graph = True

            json_data: Dict[str, Any]
            if(not graph):
                json_data = {"data": [], "graph": "false"}
                for line in f_contents:
                    contents_of_line: List[str] = line.split()
                    json_data["data"].append(contents_of_line)

            else:
                json_data = {"data": [], "graph": "true"}
                for line in f_contents:
                    contents_of_line = line.split()

                    if('Index' in contents_of_line):
                        # line_set = remove_duplicate_items_from_list(
                        #     contents_of_line)
                        line_set: List[str] = contents_of_line

                        if(line_set != curernt_headers):
                            curernt_headers = line_set
                            json_data["data"].append(
                                {"labels": [], "x": [], "y": []})
                            index: int = len(json_data["data"]) - 1
                            for x in range(2, len(curernt_headers)):
                                json_data["data"][index]["y"].append([])

                            for x in range(1, len(curernt_headers)):
                                json_data["data"][index]["labels"].append(
                                    curernt_headers[x])
                                total_number_of_tables += 1

                    else:
                        m: Optional[re.Match] = re.match('[0-9]+', line)
                        if(m):
                            index = len(json_data["data"]) - 1
                            data: Dict[str, Any] = json_data["data"][index]
                            data["x"].append(contents_of_line[1])

                            for x in range(len(data["y"])):
                                data["y"][x].append(contents_of_line[x+2])
                json_data["total_number_of_tables"] = total_number_of_tables -\
                    len(json_data["data"])
        return json_data

    except IOError as e:
        print('Cannot Open File')
        raise e


# def remove_duplicate_items_from_list(line_list):
#     res = []
#     for i in line_list:
#         if i not in res:
#             res.append(i)
#     return res


# for testing provide the filepath as command line argument
if __name__ == "__main__":

    filePath: str = sys.argv[1]
    print(extract_data_from_ngspice_output(filePath))
