export const FETCH_LIBRARIES = 'FETCH_LIBRARIES'
export const TOGGLE_COLLAPSE = 'TOGGLE_COLLAPSE'
export const FETCH_COMPONENTS = 'FETCH_COMPONENTS'
export const TOGGLE_SIMULATE = 'TOGGLE_SIMULATE'

export const GET_COMP_PROPERTIES = 'GET_COMP_PROPERTIES'
export const SET_COMP_PROPERTIES = 'SET_COMP_PROPERTIES'
export const CLOSE_COMP_PROPERTIES = 'CLOSE_COMP_PROPERTIES'

export const SET_NETLIST = 'SET_NETLIST'
export const SET_TITLE = 'SET_TITLE'
export const SET_MODEL = 'SET_MODEL'
export const SET_CONTROL_LINE = 'SET_CONTROL_LINE'
export const SET_CONTROL_BLOCK = 'SET_CONTROL_BLOCK'

export const SET_RESULT_TITLE = 'SET_RESULT_TITLE'
export const SET_RESULT_GRAPH = 'SET_RESULT_GRAPH'
export const SET_RESULT_TEXT = 'SET_RESULT_TEXT'

export const USER_LOADING = 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL'
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGOUT_SUCCESSFUL = 'LOGOUT_SUCCESSFUL'
export const LOADING_FAILED = 'LOADING_FAILED'

export const SAVE_SCHEMATICS = 'SAVE_SCHEMATICS'
export const SET_SCH_SAVED = 'SET_SCH_SAVED'
export const SET_SCH_TITLE = 'SET_SCH_TITLE'
export const SET_SCH_DESCRIPTION = 'SET_SCH_DESCRIPTION'
export const SET_SCH_XML_DATA = 'SET_SCH_XML_DATA'

export const FETCH_SCHEMATICS = 'FETCH_SCHEMATICS'
